"""Platform-agnostic robot command adapter interface."""
from __future__ import annotations

from typing import Protocol


class RobotCommandAdapter(Protocol):
    def connect(self) -> None: ...

    def prepare(self) -> None: ...

    def enter_motion_mode(self) -> None: ...

    def send_velocity(self, vx: float, vy: float = 0.0, wz: float = 0.0) -> None: ...

    def stop(self) -> None: ...

    def close(self) -> None: ...
