"""Domain layer: pure platform-independent value objects and invariants.

No vendor SDK imports. No filesystem I/O. No network I/O.
No environment variable reads. No subprocess execution. No sleeping.
No global mutable registration. No implicit configuration loading.
"""
from calibration_skill.domain.enums import (
    ALL_KNOWN_CAPABILITIES,
    ALLOWED_LIFECYCLE_TRANSITIONS,
    CAPABILITY_BATTERY_TELEMETRY,
    CAPABILITY_BODY_VELOCITY_TELEMETRY,
    CAPABILITY_COMMAND_ACKNOWLEDGEMENT,
    CAPABILITY_COMMAND_TTL,
    CAPABILITY_CONNECT,
    CAPABILITY_DISCONNECT,
    CAPABILITY_DRY_RUN,
    CAPABILITY_EMERGENCY_STOP,
    CAPABILITY_EXPLICIT_STOP,
    CAPABILITY_FIRMWARE_VERSION_REPORTING,
    CAPABILITY_HIGH_LEVEL_BODY_VELOCITY_COMMAND,
    CAPABILITY_IMU_TELEMETRY,
    CAPABILITY_LOCOMOTION_MODE_TRANSITION,
    CAPABILITY_OPERATOR_CONFIRMATION,
    CAPABILITY_PLATFORM_VERSION_REPORTING,
    CAPABILITY_POSE_ODOMETRY_TELEMETRY,
    CAPABILITY_ROBOT_MODE_OBSERVATION,
    CAPABILITY_SIMULATOR,
    CAPABILITY_STATE_STREAM,
    CAPABILITY_VELOCITY_X,
    CAPABILITY_VELOCITY_Y,
    CAPABILITY_YAW_HEADING_TELEMETRY,
    CAPABILITY_YAW_RATE,
    CapabilitySupport,
    CommandDisposition,
    CompensationAction,
    ConnectionState,
    CoordinateFrame,
    EvidenceLevel,
    ImplementationMaturity,
    MotionLifecycleState,
    PreflightStatus,
    ProfileStatus,
    RobotMorphology,
    RobotPlatform,
    SkillOperationStatus,
    TrialStatus,
)
from calibration_skill.domain.errors import (
    ERROR_ADAPTER_DISCONNECTED,
    ERROR_CAPABILITY_UNAVAILABLE,
    ERROR_CAPABILITY_UNVERIFIED,
    ERROR_COMMAND_EXPIRED,
    ERROR_COMMAND_OUTSIDE_SAFETY_ENVELOPE,
    ERROR_CONFIGURATION_INVALID,
    ERROR_CONFIGURATION_MISSING,
    ERROR_INTERNAL_ERROR,
    ERROR_INVALID_DURATION,
    ERROR_INVALID_FRAME,
    ERROR_INVALID_IDENTIFIER,
    ERROR_INVALID_QUATERNION,
    ERROR_INVALID_SAFETY_POLICY,
    ERROR_INVALID_TIMEOUT,
    ERROR_INVALID_TIMESTAMP,
    ERROR_NON_FINITE_VALUE,
    ERROR_OPERATOR_AUTHORIZATION_EXPIRED,
    ERROR_OPERATOR_AUTHORIZATION_REQUIRED,
    ERROR_PRECONDITION_FAILED,
    ERROR_PROVENANCE_INVALID,
    ERROR_SCHEMA_VERSION_UNSUPPORTED,
    ERROR_SERIALIZATION_FAILED,
    ERROR_STOP_UNACKNOWLEDGED,
    ERROR_TELEMETRY_STALE,
    ERROR_TELEMETRY_UNAVAILABLE,
    ERROR_UNSUPPORTED_PLATFORM,
    ERROR_VALIDATION_FAILED,
    ERROR_WRONG_MOTION_STATE,
    DomainError,
    domain_error,
    validation_error,
)
from calibration_skill.domain.identity import RobotIdentity
from calibration_skill.domain.capabilities import (
    CapabilityDescriptor,
    CapabilityNegotiationResult,
    CapabilityRecord,
    negotiate_capabilities,
)
from calibration_skill.domain.readiness import (
    ALL_READINESS_KEYS,
    READINESS_ARCHITECTURE_ENFORCEMENT,
    READINESS_DETERMINISTIC_CODECS,
    READINESS_DOMAIN_CONTRACTS,
    READINESS_G1_ADAPTER,
    READINESS_GO1_ADAPTER,
    READINESS_HARDWARE_VERIFICATION,
    READINESS_K1_ADAPTER_MIGRATION,
    READINESS_MOCK_ADAPTER,
    READINESS_PORT_INTERFACES,
    READINESS_RELEASE,
    READINESS_UNIFIED_SKILL_RUNTIME,
    READINESS_VERSIONED_SCHEMAS,
    ReadinessEntry,
    ReadinessModel,
)
from calibration_skill.domain.motion import (
    CommandReceipt,
    VelocityCommand,
    validate_lifecycle_transition,
)
from calibration_skill.domain.telemetry import (
    Pose3D,
    Quaternion,
    TelemetryFreshness,
    TelemetrySample,
    Twist3D,
    Vector3,
)
from calibration_skill.domain.safety import (
    OperatorAuthorization,
    PreflightCheck,
    PreflightReport,
    SafetyEnvelope,
)
from calibration_skill.domain.calibration import (
    CalibrationDataset,
    CalibrationModel,
    CalibrationProfile,
    CompensationDecision,
    EnvironmentDescriptor,
    ExecutionAuditRecord,
    TrialPlan,
    TrialResult,
)

__all__ = [
    # Enums
    "RobotPlatform",
    "RobotMorphology",
    "CoordinateFrame",
    "ConnectionState",
    "MotionLifecycleState",
    "CapabilitySupport",
    "EvidenceLevel",
    "ImplementationMaturity",
    "CommandDisposition",
    "SkillOperationStatus",
    "PreflightStatus",
    "TrialStatus",
    "CompensationAction",
    "ProfileStatus",
    # Capability constants
    "ALL_KNOWN_CAPABILITIES",
    "CAPABILITY_CONNECT",
    "CAPABILITY_DISCONNECT",
    "CAPABILITY_HIGH_LEVEL_BODY_VELOCITY_COMMAND",
    "CAPABILITY_VELOCITY_X",
    "CAPABILITY_VELOCITY_Y",
    "CAPABILITY_YAW_RATE",
    "CAPABILITY_EXPLICIT_STOP",
    "CAPABILITY_LOCOMOTION_MODE_TRANSITION",
    "CAPABILITY_ROBOT_MODE_OBSERVATION",
    "CAPABILITY_BODY_VELOCITY_TELEMETRY",
    "CAPABILITY_POSE_ODOMETRY_TELEMETRY",
    "CAPABILITY_IMU_TELEMETRY",
    "CAPABILITY_YAW_HEADING_TELEMETRY",
    "CAPABILITY_BATTERY_TELEMETRY",
    "CAPABILITY_COMMAND_ACKNOWLEDGEMENT",
    "CAPABILITY_STATE_STREAM",
    "CAPABILITY_EMERGENCY_STOP",
    "CAPABILITY_SIMULATOR",
    "CAPABILITY_DRY_RUN",
    "CAPABILITY_COMMAND_TTL",
    "CAPABILITY_OPERATOR_CONFIRMATION",
    "CAPABILITY_PLATFORM_VERSION_REPORTING",
    "CAPABILITY_FIRMWARE_VERSION_REPORTING",
    "ALLOWED_LIFECYCLE_TRANSITIONS",
    # Errors
    "DomainError",
    "domain_error",
    "validation_error",
    "ERROR_CONFIGURATION_MISSING",
    "ERROR_CONFIGURATION_INVALID",
    "ERROR_UNSUPPORTED_PLATFORM",
    "ERROR_CAPABILITY_UNAVAILABLE",
    "ERROR_CAPABILITY_UNVERIFIED",
    "ERROR_PRECONDITION_FAILED",
    "ERROR_ADAPTER_DISCONNECTED",
    "ERROR_WRONG_MOTION_STATE",
    "ERROR_OPERATOR_AUTHORIZATION_REQUIRED",
    "ERROR_OPERATOR_AUTHORIZATION_EXPIRED",
    "ERROR_COMMAND_EXPIRED",
    "ERROR_COMMAND_OUTSIDE_SAFETY_ENVELOPE",
    "ERROR_TELEMETRY_UNAVAILABLE",
    "ERROR_TELEMETRY_STALE",
    "ERROR_STOP_UNACKNOWLEDGED",
    "ERROR_SCHEMA_VERSION_UNSUPPORTED",
    "ERROR_SERIALIZATION_FAILED",
    "ERROR_PROVENANCE_INVALID",
    "ERROR_INTERNAL_ERROR",
    "ERROR_VALIDATION_FAILED",
    "ERROR_INVALID_IDENTIFIER",
    "ERROR_INVALID_TIMESTAMP",
    "ERROR_INVALID_DURATION",
    "ERROR_INVALID_TIMEOUT",
    "ERROR_NON_FINITE_VALUE",
    "ERROR_INVALID_QUATERNION",
    "ERROR_INVALID_FRAME",
    "ERROR_INVALID_SAFETY_POLICY",
    # Identity
    "RobotIdentity",
    # Capabilities
    "CapabilityRecord",
    "CapabilityDescriptor",
    "CapabilityNegotiationResult",
    "negotiate_capabilities",
    # Readiness
    "ReadinessEntry",
    "ReadinessModel",
    "ALL_READINESS_KEYS",
    "READINESS_DOMAIN_CONTRACTS",
    "READINESS_PORT_INTERFACES",
    "READINESS_VERSIONED_SCHEMAS",
    "READINESS_DETERMINISTIC_CODECS",
    "READINESS_ARCHITECTURE_ENFORCEMENT",
    "READINESS_MOCK_ADAPTER",
    "READINESS_K1_ADAPTER_MIGRATION",
    "READINESS_G1_ADAPTER",
    "READINESS_GO1_ADAPTER",
    "READINESS_UNIFIED_SKILL_RUNTIME",
    "READINESS_HARDWARE_VERIFICATION",
    "READINESS_RELEASE",
    # Motion
    "VelocityCommand",
    "CommandReceipt",
    "validate_lifecycle_transition",
    # Telemetry
    "Vector3",
    "Quaternion",
    "Pose3D",
    "Twist3D",
    "TelemetryFreshness",
    "TelemetrySample",
    # Safety
    "SafetyEnvelope",
    "OperatorAuthorization",
    "PreflightCheck",
    "PreflightReport",
    # Calibration
    "EnvironmentDescriptor",
    "TrialPlan",
    "TrialResult",
    "CalibrationDataset",
    "CalibrationModel",
    "CalibrationProfile",
    "CompensationDecision",
    "ExecutionAuditRecord",
]
